[package]
name = "noire-ipc"
description = "Shared D-Bus types and adapters for Noire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
noire-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
zbus = { workspace = true, optional = true }

[features]
dbus = ["dep:thiserror", "dep:tokio", "dep:zbus"]
default = []

[lints]
workspace = true
