[package]
name = "noirectl"
description = "Command-line control client for Noire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
noire-core.workspace = true
noire-ipc = { workspace = true, features = ["dbus"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
zbus.workspace = true

[lints]
workspace = true
