[package]
name = "noirectl"
description = "Command-line control client for Noire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
noire-core.workspace = true
noire-ipc.workspace = true

[lints]
workspace = true
