[package]
name = "noired"
description = "Noire per-user noise-reduction daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true, optional = true }
clap.workspace = true
noire-config.workspace = true
noire-core.workspace = true
noire-ipc.workspace = true
noire-model.workspace = true
noire-model-fastenhancer = { workspace = true, optional = true }
noire-pipewire.workspace = true
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
thiserror.workspace = true
zbus = { workspace = true, optional = true }

[dev-dependencies]
futures-util.workspace = true
proptest.workspace = true

[features]
default = ["runtime", "pipewire-backend"]
pipewire-backend = ["noire-pipewire/pipewire-backend", "dep:noire-model-fastenhancer"]
native-test = ["pipewire-backend", "noire-pipewire/native-test"]
runtime = ["dep:anyhow", "dep:tokio", "dep:tracing", "dep:tracing-subscriber", "dep:zbus", "noire-ipc/dbus"]

[lints]
workspace = true
