[package]
name = "noire-ui"
description = "GPUI desktop interface for Noire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "noire"
path = "src/main.rs"

[dependencies]
clap.workspace = true
futures-util = { workspace = true, optional = true }
gpui = { workspace = true, optional = true }
ksni = { workspace = true, optional = true }
noire-core.workspace = true
noire-ipc.workspace = true
serde = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
zbus = { workspace = true, optional = true }

[dev-dependencies]
noire-config.workspace = true
noired.workspace = true

[features]
default = ["gpui-ui"]
gpui-ui = [
    "dep:futures-util",
    "dep:gpui",
    "dep:ksni",
    "dep:serde",
    "dep:tokio",
    "dep:toml",
    "dep:zbus",
    "noire-ipc/dbus",
]

[lints]
workspace = true
